[package]
name = "rust-interact"
version = "0.0.0"
authors = ["you"]
edition = "2024"
publish = false

[[bin]]
name = "rust-interact"
path = "src/interactor_main.rs"

[dependencies.rust-snippets-generator-test]
path = ".."

[dependencies.multiversx-sc-snippets]
version = "0.66.2"
path = "../../../../framework/snippets"

# [workspace]




[patch.crates-io]
multiversx-chain-vm-executor = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "a72bba88d41c31fff4502811c8835a2296072017" }
multiversx-chain-vm-executor-wasmer-experimental = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "a72bba88d41c31fff4502811c8835a2296072017" }
