[[bin]]
name = "git-scraper"
path = "src/scraper.rs"

[package]
name = "git-scraper"
version = "0.0.0"
publish = false
edition = "2024"
authors = ["you"]

[dependencies]
reqwest = { version = "0.13", features = ["rustls", "blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
toml = "1.0"

[workspace]
members = ["."]


[patch.crates-io]
multiversx-chain-vm-executor = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "1e87b8f34074954f7b3e0d5665de6fd1c4cc6d9c" }
multiversx-chain-vm-executor-wasmer-experimental = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "1e87b8f34074954f7b3e0d5665de6fd1c4cc6d9c" }
