[[bin]]
name = "git-scraper"
path = "src/scraper.rs"

[package]
name = "git-scraper"
version = "0.0.0"
publish = false
edition = "2024"
authors = ["you"]

[dependencies]
reqwest = { version = "0.13", features = ["rustls", "blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
toml = "1.0"

[workspace]
members = ["."]


[patch.crates-io]
multiversx-chain-vm-executor = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "830f3efa2a1c8103424e4dd0c65b786e1f8305cf" }
multiversx-chain-vm-executor-wasmer-experimental = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "830f3efa2a1c8103424e4dd0c65b786e1f8305cf" }
