[package]
name = "gas_tests"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "src/gas_tests.rs"

[dependencies.multiversx-sc]
version = "0.66.2"
path = "../../../framework/base"

[dev-dependencies.multiversx-sc-scenario]
version = "0.66.2"
path = "../../../framework/scenario"

[dependencies.multiversx-chain-vm-wasmer-prod]
path = "../../../chain/wasmer-prod"
optional = true

[features]
wasmer-prod = ["multiversx-chain-vm-wasmer-prod"]
wasmer-experimental = ["multiversx-sc-scenario/wasmer-experimental"]

[workspace]
members = ["."]

[patch.crates-io]
multiversx-chain-vm-executor = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "a72bba88d41c31fff4502811c8835a2296072017" }
multiversx-chain-vm-executor-wasmer-experimental = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "a72bba88d41c31fff4502811c8835a2296072017" }
