[package]
name = "multiversx-chain-vm-wasmer-prod"
version = "0.0.0"
edition = "2024"
publish = false

description = "MultiversX VM adapter for the Wasmer Production executor"

[lib]
path = "src/wasmer_prod.rs"

[dependencies]
home = "=0.5.1" # downgrading, >= 0.5.2 requires rustc 1.88

[dependencies.multiversx-chain-core]
version = "=0.23.1"
path = "../core"


[dependencies.multiversx-chain-vm]
version = "=0.23.1"
path = "../vm"

[dependencies.multiversx-chain-vm-executor]
version = "=0.5.1"

[dependencies.multiversx-chain-vm-executor-wasmer]
version = "=0.5.1"
default-features = false
git = "https://github.com/xorewa/mx-vm-executor-rs"
rev = "c998a4531f45aa983f4a37ebfe3f4637e3a65fe8"

[workspace]
members = ["."]

[patch.crates-io]
multiversx-chain-vm-executor = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "c998a4531f45aa983f4a37ebfe3f4637e3a65fe8" }
multiversx-chain-vm-executor-wasmer-experimental = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "c998a4531f45aa983f4a37ebfe3f4637e3a65fe8" }
