[package]
name = "format-tests"
version = "0.0.0"
edition = "2024"
publish = false

[[bin]]
name = "format-tests"
path = "src/format_tests.rs"

[dependencies.multiversx-sc]
version = "=0.66.2"
path = "../../../framework/base"

[dependencies.multiversx-sc-scenario]
version = "=0.66.2"
path = "../../../framework/scenario"

[dependencies.multiversx-chain-vm]
version = "=0.23.1"
path = "../../../chain/vm"

[dependencies]
hex = "0.4"

[dev-dependencies]
glob = "0.3"

[workspace]
members = ["."]

[patch.crates-io]
multiversx-chain-vm-executor = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "c998a4531f45aa983f4a37ebfe3f4637e3a65fe8" }
multiversx-chain-vm-executor-wasmer-experimental = { git = "https://github.com/xorewa/mx-vm-executor-rs", rev = "c998a4531f45aa983f4a37ebfe3f4637e3a65fe8" }
