#!/usr/bin/env bash
# ------------------------------------------------------------
# contracts/drwa/deploy_drwa.sh
# Deploy the full DRWA V1 contract suite in the correct order.
# ------------------------------------------------------------
#   Wallet (PEM) that will fund every deployment:
#   erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th
#
#   Governance parameters (adjust as needed before running):
#     QUORUM                – signatures needed to approve a proposal
#     PROPOSAL_TTL_ROUNDS  – how many rounds a proposal lives
#     SIGNERS               – semicolon‑separated list of multisig signers
# ------------------------------------------------------------

# ------------------------------------------------------------------
# 1️⃣  GLOBAL SETTINGS (you can change them here before running)
# ------------------------------------------------------------------
WALLET_PEM="../../../sdk/core/src/test_wallets/alice.pem"
ALICE_ADDRESS="erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th"
QUORUM=1                     # example: 2‑out‑of‑N
PROPOSAL_TTL=1000            # example: 100 rounds
SIGNERS="${ALICE_ADDRESS}"   # <-- replace with real signer addresses

# ------------------------------------------------------------------
# 2️⃣  TOOL SELECTION – we use the source variant (cargo‑run) because it
#     works without a pre‑installed binary and respects the repo layout.
# ------------------------------------------------------------------
BASE=(cargo run --manifest-path ../../Cargo.toml --bin sc-meta --)
TX_CMD=tx
TX_TOOL=("${BASE[@]}" "${TX_CMD}")
DATA_TOOL=("${BASE[@]}" data)

# ------------------------------------------------------------------
# 3️⃣  NETWORK & ENDPOINT
# ------------------------------------------------------------------
NETWORK=devnet               # keep devnet for the guide; change if needed
case "${NETWORK}" in
    devnet)   PROXY=https://latina-pharmacy-webmasters-article.trycloudflare.com;   CHAIN=D ;;
    testnet)  PROXY=https://testnet-gateway.multiversx.com;  CHAIN=T ;;
    mainnet)  PROXY=https://gateway.multiversx.com;          CHAIN=1 ;;
    chain-simulator) PROXY=http://localhost:8085;          CHAIN=chain ;;
esac

# ------------------------------------------------------------------
# 4️⃣  PATHS TO WASM artefacts (generated by `sc-meta all build`)
# ------------------------------------------------------------------
WASM_AUTH_ADMIN="../../contracts/drwa/drwa-auth-admin/output/drwa-auth-admin.wasm"
WASM_POLICY_REG="../../contracts/drwa/policy-registry/output/drwa-policy-registry.wasm"
WASM_IDENTITY_REG="../../contracts/drwa/identity-registry/output/drwa-identity-registry.wasm"
WASM_ASSET_MGR="../../contracts/drwa/asset-manager/output/drwa-asset-manager.wasm"
WASM_ATTESTATION="../../contracts/drwa/attestation/output/drwa-attestation.wasm"

# ------------------------------------------------------------------
# 5️⃣  DEPLOY drwa‑auth‑admin (governance core)
# ------------------------------------------------------------------
echo "▶ Deploying drwa‑auth‑admin (governance core)…"
GOV_ADDR=$("${TX_TOOL[@]}" deploy \
    --bytecode "${WASM_AUTH_ADMIN}" \
    --pem="${WALLET_PEM}" \
    --gas-limit=100_000_000 \
    --arguments "${QUORUM}" "${PROPOSAL_TTL}" "address:${SIGNE``RS}" \
    --proxy="${PROXY}" \
    --chain="${CHAIN}" \
    --send \
    --outfile="auth_admin_deploy.json" \
    || { echo "❌ drwa‑auth‑admin deployment failed"; exit 1; })
# Extract the contract address from the JSON output
GOV_ADDR=$("${DATA_TOOL[@]}" parse --file=auth_admin_deploy.json \
    --expression="data['contractAddress']")

echo "   → governance address: ${GOV_ADDR}"

# ------------------------------------------------------------------
# 6️⃣  DEPLOY policy‑registry
# ------------------------------------------------------------------
echo "▶ Deploying policy‑registry…"
POLICY_ADDR=$("${TX_TOOL[@]}" deploy \
    --bytecode "${WASM_POLICY_REG}" \
    --pem="${WALLET_PEM}" \
    --gas-limit=80_000_000 \
    --arguments "address:${GOV_ADDR}" \
    --proxy="${PROXY}" \
    --chain="${CHAIN}" \
    --send \
    --outfile="policy_deploy.json" \
    || { echo "❌ policy‑registry deployment failed"; exit 1; })
POLICY_ADDR=$("${DATA_TOOL[@]}" parse --file=policy_deploy.json \
    --expression="data['contractAddress']")

echo "   → policy‑registry address: ${POLICY_ADDR}"

# ------------------------------------------------------------------
# 7️⃣  DEPLOY identity‑registry
# ------------------------------------------------------------------
echo "▶ Deploying identity‑registry…"
IDENTITY_ADDR=$("${TX_TOOL[@]}" deploy \
    --bytecode "${WASM_IDENTITY_REG}" \
    --pem="${WALLET_PEM}" \
    --gas-limit=80_000_000 \
    --arguments "address:${GOV_ADDR}" \
    --proxy="${PROXY}" \
    --chain="${CHAIN}" \
    --send \
    --outfile="identity_deploy.json" \
    || { echo "❌ identity‑registry deployment failed"; exit 1; })
IDENTITY_ADDR=$("${DATA_TOOL[@]}" parse --file=identity_deploy.json \
    --expression="data['contractAddress']")

echo "   → identity‑registry address: ${IDENTITY_ADDR}"

# ------------------------------------------------------------------
# 8️⃣  DEPLOY asset‑manager
# ------------------------------------------------------------------
echo "▶ Deploying asset‑manager…"
ASSET_ADDR=$("${TX_TOOL[@]}" deploy \
    --bytecode "${WASM_ASSET_MGR}" \
    --pem="${WALLET_PEM}" \
    --gas-limit=100_000_000 \
    --arguments "address:${GOV_ADDR}" \
    --proxy="${PROXY}" \
    --chain="${CHAIN}" \
    --send \
    --outfile="asset_deploy.json" \
    || { echo "❌ asset‑manager deployment failed"; exit 1; })
ASSET_ADDR=$("${DATA_TOOL[@]}" parse --file=asset_deploy.json \
    --expression="data['contractAddress']")

echo "   → asset‑manager address: ${ASSET_ADDR}"

# ------------------------------------------------------------------
# 9️⃣  DEPLOY attestation
# ------------------------------------------------------------------
# Choose an auditor address – here we reuse Alice's address,
# but you can replace it with any other address you control.
AUDITOR_ADDR="${ALICE_ADDRESS}"
echo "▶ Deploying attestation (auditor=${AUDITOR_ADDR})…"
ATTEST_ADDR=$("${TX_TOOL[@]}" deploy \
    --bytecode "${WASM_ATTESTATION}" \
    --pem="${WALLET_PEM}" \
    --gas-limit=80_000_000 \
    --arguments "address:${AUDITOR_ADDR}" \
    --proxy="${PROXY}" \
    --chain="${CHAIN}" \
    --send \
    --outfile="attest_deploy.json" \
    || { echo "❌ attestation deployment failed"; exit 1; })
ATTEST_ADDR=$("${DATA_TOOL[@]}" parse --file=attest_deploy.json \
    --expression="data['contractAddress']")

echo "   → attestation address: ${ATTEST_ADDR}"

# ------------------------------------------------------------------
# 10️⃣  OPTIONAL: Wire asset‑manager → policy‑registry (mandatory in practice)
# ------------------------------------------------------------------
# The only required post‑deployment configuration is to set the
# policy‑registry address inside the asset‑manager via the governance
# contract.  This call is *not* executed automatically; it is left here
# as a ready‑to‑run command for the operator.
cat <<'EOF' > set_policy_registry.sh
#!/usr/bin/env bash
# Usage: ./set_policy_registry.sh <proposal‑id>
# The proposal must be created and signed by the multisig signers.
# ------------------------------------------------------------
# Example (run after the above script finishes):
#   PROPOSAL_ID=$(sc-meta propose \
#       --contract "${GOV_ADDR}" \
#       --function setPolicyRegistryAddress \
#       --args "policy_registry_address:${POLICY_ADDR}" \
#       --sender "${WALLET}")
#   # each signer signs...
#   sc-meta sign --proposal-id "${PROPOSAL_ID}" --signer <SIGNER>
#   sc-meta perform --proposal-id "${PROPOSAL_ID}" --sender "${WALLET}"
EOF
chmod +x set_policy_registry.sh

echo "✅ All contracts deployed (addresses stored in env variables)."
echo "   • Governance (drwa‑auth‑admin) : ${GOV_ADDR}"
echo "   • Policy‑registry            : ${POLICY_ADDR}"
echo "   • Identity‑registry          : ${IDENTITY_ADDR}"
echo "   • Asset‑manager              : ${ASSET_ADDR}"
echo "   • Attestation                : ${ATTEST_ADDR}"
echo ""
echo "Next step: run ./set_policy_registry.sh (or copy‑paste the proposal commands) to wire the asset‑manager."
